//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7/6/2011 11:44:15 AM
namespace FacetedWorlds.MyCon.DevLink.DevLinkServiceReference
{
    
    /// <summary>
    /// There are no comments for devlink2011Entities in the schema.
    /// </summary>
    public partial class devlink2011Entities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new devlink2011Entities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public devlink2011Entities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("devlink2011Model", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("FacetedWorlds.MyCon.DevLink.DevLinkServiceReference", typeName.Substring(16)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("FacetedWorlds.MyCon.DevLink.DevLinkServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("devlink2011Model.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for rooms in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<room> rooms
        {
            get
            {
                if ((this._rooms == null))
                {
                    this._rooms = base.CreateQuery<room>("rooms");
                }
                return this._rooms;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<room> _rooms;
        /// <summary>
        /// There are no comments for sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<session> sessions
        {
            get
            {
                if ((this._sessions == null))
                {
                    this._sessions = base.CreateQuery<session>("sessions");
                }
                return this._sessions;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<session> _sessions;
        /// <summary>
        /// There are no comments for sessionlevels in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<sessionlevel> sessionlevels
        {
            get
            {
                if ((this._sessionlevels == null))
                {
                    this._sessionlevels = base.CreateQuery<sessionlevel>("sessionlevels");
                }
                return this._sessionlevels;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<sessionlevel> _sessionlevels;
        /// <summary>
        /// There are no comments for speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<speaker> speakers
        {
            get
            {
                if ((this._speakers == null))
                {
                    this._speakers = base.CreateQuery<speaker>("speakers");
                }
                return this._speakers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<speaker> _speakers;
        /// <summary>
        /// There are no comments for sponsors in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<sponsor> sponsors
        {
            get
            {
                if ((this._sponsors == null))
                {
                    this._sponsors = base.CreateQuery<sponsor>("sponsors");
                }
                return this._sponsors;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<sponsor> _sponsors;
        /// <summary>
        /// There are no comments for sponsorlevels in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<sponsorlevel> sponsorlevels
        {
            get
            {
                if ((this._sponsorlevels == null))
                {
                    this._sponsorlevels = base.CreateQuery<sponsorlevel>("sponsorlevels");
                }
                return this._sponsorlevels;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<sponsorlevel> _sponsorlevels;
        /// <summary>
        /// There are no comments for timeslots in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<timeslot> timeslots
        {
            get
            {
                if ((this._timeslots == null))
                {
                    this._timeslots = base.CreateQuery<timeslot>("timeslots");
                }
                return this._timeslots;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<timeslot> _timeslots;
        /// <summary>
        /// There are no comments for tracks in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<track> tracks
        {
            get
            {
                if ((this._tracks == null))
                {
                    this._tracks = base.CreateQuery<track>("tracks");
                }
                return this._tracks;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<track> _tracks;
        /// <summary>
        /// There are no comments for rooms in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTorooms(room room)
        {
            base.AddObject("rooms", room);
        }
        /// <summary>
        /// There are no comments for sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTosessions(session session)
        {
            base.AddObject("sessions", session);
        }
        /// <summary>
        /// There are no comments for sessionlevels in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTosessionlevels(sessionlevel sessionlevel)
        {
            base.AddObject("sessionlevels", sessionlevel);
        }
        /// <summary>
        /// There are no comments for speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTospeakers(speaker speaker)
        {
            base.AddObject("speakers", speaker);
        }
        /// <summary>
        /// There are no comments for sponsors in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTosponsors(sponsor sponsor)
        {
            base.AddObject("sponsors", sponsor);
        }
        /// <summary>
        /// There are no comments for sponsorlevels in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTosponsorlevels(sponsorlevel sponsorlevel)
        {
            base.AddObject("sponsorlevels", sponsorlevel);
        }
        /// <summary>
        /// There are no comments for timeslots in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTotimeslots(timeslot timeslot)
        {
            base.AddObject("timeslots", timeslot);
        }
        /// <summary>
        /// There are no comments for tracks in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTotracks(track track)
        {
            base.AddObject("tracks", track);
        }
    }
    /// <summary>
    /// There are no comments for devlink2011Model.room in the schema.
    /// </summary>
    /// <KeyProperties>
    /// roomid
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("rooms")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("roomid")]
    public partial class room : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new room object.
        /// </summary>
        /// <param name="roomid">Initial value of roomid.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static room Createroom(int roomid)
        {
            room room = new room();
            room.roomid = roomid;
            return room;
        }
        /// <summary>
        /// There are no comments for Property roomid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int roomid
        {
            get
            {
                return this._roomid;
            }
            set
            {
                this.OnroomidChanging(value);
                this._roomid = value;
                this.OnroomidChanged();
                this.OnPropertyChanged("roomid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _roomid;
        partial void OnroomidChanging(int value);
        partial void OnroomidChanged();
        /// <summary>
        /// There are no comments for Property building in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string building
        {
            get
            {
                return this._building;
            }
            set
            {
                this.OnbuildingChanging(value);
                this._building = value;
                this.OnbuildingChanged();
                this.OnPropertyChanged("building");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _building;
        partial void OnbuildingChanging(string value);
        partial void OnbuildingChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property sponsorid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> sponsorid
        {
            get
            {
                return this._sponsorid;
            }
            set
            {
                this.OnsponsoridChanging(value);
                this._sponsorid = value;
                this.OnsponsoridChanged();
                this.OnPropertyChanged("sponsorid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _sponsorid;
        partial void OnsponsoridChanging(global::System.Nullable<int> value);
        partial void OnsponsoridChanged();
        /// <summary>
        /// There are no comments for sponsor in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public sponsor sponsor
        {
            get
            {
                return this._sponsor;
            }
            set
            {
                this._sponsor = value;
                this.OnPropertyChanged("sponsor");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private sponsor _sponsor;
        /// <summary>
        /// There are no comments for sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<session> sessions
        {
            get
            {
                return this._sessions;
            }
            set
            {
                this._sessions = value;
                this.OnPropertyChanged("sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<session> _sessions = new global::System.Data.Services.Client.DataServiceCollection<session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for devlink2011Model.session in the schema.
    /// </summary>
    /// <KeyProperties>
    /// sessionid
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("sessions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("sessionid")]
    public partial class session : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new session object.
        /// </summary>
        /// <param name="sessionid">Initial value of sessionid.</param>
        /// <param name="title">Initial value of title.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static session Createsession(int sessionid, string title)
        {
            session session = new session();
            session.sessionid = sessionid;
            session.title = title;
            return session;
        }
        /// <summary>
        /// There are no comments for Property sessionid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int sessionid
        {
            get
            {
                return this._sessionid;
            }
            set
            {
                this.OnsessionidChanging(value);
                this._sessionid = value;
                this.OnsessionidChanged();
                this.OnPropertyChanged("sessionid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _sessionid;
        partial void OnsessionidChanging(int value);
        partial void OnsessionidChanged();
        /// <summary>
        /// There are no comments for Property trackid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> trackid
        {
            get
            {
                return this._trackid;
            }
            set
            {
                this.OntrackidChanging(value);
                this._trackid = value;
                this.OntrackidChanged();
                this.OnPropertyChanged("trackid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _trackid;
        partial void OntrackidChanging(global::System.Nullable<int> value);
        partial void OntrackidChanged();
        /// <summary>
        /// There are no comments for Property sessionlevelid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> sessionlevelid
        {
            get
            {
                return this._sessionlevelid;
            }
            set
            {
                this.OnsessionlevelidChanging(value);
                this._sessionlevelid = value;
                this.OnsessionlevelidChanged();
                this.OnPropertyChanged("sessionlevelid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _sessionlevelid;
        partial void OnsessionlevelidChanging(global::System.Nullable<int> value);
        partial void OnsessionlevelidChanged();
        /// <summary>
        /// There are no comments for Property title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string title
        {
            get
            {
                return this._title;
            }
            set
            {
                this.OntitleChanging(value);
                this._title = value;
                this.OntitleChanged();
                this.OnPropertyChanged("title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _title;
        partial void OntitleChanging(string value);
        partial void OntitleChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property roomid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> roomid
        {
            get
            {
                return this._roomid;
            }
            set
            {
                this.OnroomidChanging(value);
                this._roomid = value;
                this.OnroomidChanged();
                this.OnPropertyChanged("roomid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _roomid;
        partial void OnroomidChanging(global::System.Nullable<int> value);
        partial void OnroomidChanged();
        /// <summary>
        /// There are no comments for Property timeslotid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> timeslotid
        {
            get
            {
                return this._timeslotid;
            }
            set
            {
                this.OntimeslotidChanging(value);
                this._timeslotid = value;
                this.OntimeslotidChanged();
                this.OnPropertyChanged("timeslotid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _timeslotid;
        partial void OntimeslotidChanging(global::System.Nullable<int> value);
        partial void OntimeslotidChanged();
        /// <summary>
        /// There are no comments for Property codepercent in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> codepercent
        {
            get
            {
                return this._codepercent;
            }
            set
            {
                this.OncodepercentChanging(value);
                this._codepercent = value;
                this.OncodepercentChanged();
                this.OnPropertyChanged("codepercent");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _codepercent;
        partial void OncodepercentChanging(global::System.Nullable<int> value);
        partial void OncodepercentChanged();
        /// <summary>
        /// There are no comments for Property slidepercent in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> slidepercent
        {
            get
            {
                return this._slidepercent;
            }
            set
            {
                this.OnslidepercentChanging(value);
                this._slidepercent = value;
                this.OnslidepercentChanged();
                this.OnPropertyChanged("slidepercent");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _slidepercent;
        partial void OnslidepercentChanging(global::System.Nullable<int> value);
        partial void OnslidepercentChanged();
        /// <summary>
        /// There are no comments for Property sponsorid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> sponsorid
        {
            get
            {
                return this._sponsorid;
            }
            set
            {
                this.OnsponsoridChanging(value);
                this._sponsorid = value;
                this.OnsponsoridChanged();
                this.OnPropertyChanged("sponsorid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _sponsorid;
        partial void OnsponsoridChanging(global::System.Nullable<int> value);
        partial void OnsponsoridChanged();
        /// <summary>
        /// There are no comments for Property speakerid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> speakerid
        {
            get
            {
                return this._speakerid;
            }
            set
            {
                this.OnspeakeridChanging(value);
                this._speakerid = value;
                this.OnspeakeridChanged();
                this.OnPropertyChanged("speakerid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _speakerid;
        partial void OnspeakeridChanging(global::System.Nullable<int> value);
        partial void OnspeakeridChanged();
        /// <summary>
        /// There are no comments for room in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public room room
        {
            get
            {
                return this._room;
            }
            set
            {
                this._room = value;
                this.OnPropertyChanged("room");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private room _room;
        /// <summary>
        /// There are no comments for speaker in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public speaker speaker
        {
            get
            {
                return this._speaker;
            }
            set
            {
                this._speaker = value;
                this.OnPropertyChanged("speaker");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private speaker _speaker;
        /// <summary>
        /// There are no comments for sponsor in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public sponsor sponsor
        {
            get
            {
                return this._sponsor;
            }
            set
            {
                this._sponsor = value;
                this.OnPropertyChanged("sponsor");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private sponsor _sponsor;
        /// <summary>
        /// There are no comments for timeslot in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public timeslot timeslot
        {
            get
            {
                return this._timeslot;
            }
            set
            {
                this._timeslot = value;
                this.OnPropertyChanged("timeslot");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private timeslot _timeslot;
        /// <summary>
        /// There are no comments for sessionlevel in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public sessionlevel sessionlevel
        {
            get
            {
                return this._sessionlevel;
            }
            set
            {
                this._sessionlevel = value;
                this.OnPropertyChanged("sessionlevel");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private sessionlevel _sessionlevel;
        /// <summary>
        /// There are no comments for track in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public track track
        {
            get
            {
                return this._track;
            }
            set
            {
                this._track = value;
                this.OnPropertyChanged("track");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private track _track;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for devlink2011Model.sessionlevel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// sessionlevelid
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("sessionlevels")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("sessionlevelid")]
    public partial class sessionlevel : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new sessionlevel object.
        /// </summary>
        /// <param name="sessionlevelid">Initial value of sessionlevelid.</param>
        /// <param name="name">Initial value of name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static sessionlevel Createsessionlevel(int sessionlevelid, string name)
        {
            sessionlevel sessionlevel = new sessionlevel();
            sessionlevel.sessionlevelid = sessionlevelid;
            sessionlevel.name = name;
            return sessionlevel;
        }
        /// <summary>
        /// There are no comments for Property sessionlevelid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int sessionlevelid
        {
            get
            {
                return this._sessionlevelid;
            }
            set
            {
                this.OnsessionlevelidChanging(value);
                this._sessionlevelid = value;
                this.OnsessionlevelidChanged();
                this.OnPropertyChanged("sessionlevelid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _sessionlevelid;
        partial void OnsessionlevelidChanging(int value);
        partial void OnsessionlevelidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<session> sessions
        {
            get
            {
                return this._sessions;
            }
            set
            {
                this._sessions = value;
                this.OnPropertyChanged("sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<session> _sessions = new global::System.Data.Services.Client.DataServiceCollection<session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for devlink2011Model.speaker in the schema.
    /// </summary>
    /// <KeyProperties>
    /// speakerid
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("speakers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("speakerid")]
    public partial class speaker : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new speaker object.
        /// </summary>
        /// <param name="speakerid">Initial value of speakerid.</param>
        /// <param name="firstname">Initial value of firstname.</param>
        /// <param name="lastname">Initial value of lastname.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static speaker Createspeaker(int speakerid, string firstname, string lastname)
        {
            speaker speaker = new speaker();
            speaker.speakerid = speakerid;
            speaker.firstname = firstname;
            speaker.lastname = lastname;
            return speaker;
        }
        /// <summary>
        /// There are no comments for Property speakerid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int speakerid
        {
            get
            {
                return this._speakerid;
            }
            set
            {
                this.OnspeakeridChanging(value);
                this._speakerid = value;
                this.OnspeakeridChanged();
                this.OnPropertyChanged("speakerid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _speakerid;
        partial void OnspeakeridChanging(int value);
        partial void OnspeakeridChanged();
        /// <summary>
        /// There are no comments for Property firstname in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string firstname
        {
            get
            {
                return this._firstname;
            }
            set
            {
                this.OnfirstnameChanging(value);
                this._firstname = value;
                this.OnfirstnameChanged();
                this.OnPropertyChanged("firstname");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _firstname;
        partial void OnfirstnameChanging(string value);
        partial void OnfirstnameChanged();
        /// <summary>
        /// There are no comments for Property lastname in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string lastname
        {
            get
            {
                return this._lastname;
            }
            set
            {
                this.OnlastnameChanging(value);
                this._lastname = value;
                this.OnlastnameChanged();
                this.OnPropertyChanged("lastname");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _lastname;
        partial void OnlastnameChanging(string value);
        partial void OnlastnameChanged();
        /// <summary>
        /// There are no comments for Property company in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string company
        {
            get
            {
                return this._company;
            }
            set
            {
                this.OncompanyChanging(value);
                this._company = value;
                this.OncompanyChanged();
                this.OnPropertyChanged("company");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _company;
        partial void OncompanyChanging(string value);
        partial void OncompanyChanged();
        /// <summary>
        /// There are no comments for Property url in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string url
        {
            get
            {
                return this._url;
            }
            set
            {
                this.OnurlChanging(value);
                this._url = value;
                this.OnurlChanged();
                this.OnPropertyChanged("url");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _url;
        partial void OnurlChanging(string value);
        partial void OnurlChanged();
        /// <summary>
        /// There are no comments for Property imageurl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string imageurl
        {
            get
            {
                return this._imageurl;
            }
            set
            {
                this.OnimageurlChanging(value);
                this._imageurl = value;
                this.OnimageurlChanged();
                this.OnPropertyChanged("imageurl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _imageurl;
        partial void OnimageurlChanging(string value);
        partial void OnimageurlChanged();
        /// <summary>
        /// There are no comments for Property bio in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string bio
        {
            get
            {
                return this._bio;
            }
            set
            {
                this.OnbioChanging(value);
                this._bio = value;
                this.OnbioChanged();
                this.OnPropertyChanged("bio");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _bio;
        partial void OnbioChanging(string value);
        partial void OnbioChanged();
        /// <summary>
        /// There are no comments for Property twitter in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string twitter
        {
            get
            {
                return this._twitter;
            }
            set
            {
                this.OntwitterChanging(value);
                this._twitter = value;
                this.OntwitterChanged();
                this.OnPropertyChanged("twitter");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _twitter;
        partial void OntwitterChanging(string value);
        partial void OntwitterChanged();
        /// <summary>
        /// There are no comments for sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<session> sessions
        {
            get
            {
                return this._sessions;
            }
            set
            {
                this._sessions = value;
                this.OnPropertyChanged("sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<session> _sessions = new global::System.Data.Services.Client.DataServiceCollection<session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for devlink2011Model.sponsor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// sponsorid
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("sponsors")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("sponsorid")]
    public partial class sponsor : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new sponsor object.
        /// </summary>
        /// <param name="sponsorid">Initial value of sponsorid.</param>
        /// <param name="name">Initial value of name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static sponsor Createsponsor(int sponsorid, string name)
        {
            sponsor sponsor = new sponsor();
            sponsor.sponsorid = sponsorid;
            sponsor.name = name;
            return sponsor;
        }
        /// <summary>
        /// There are no comments for Property sponsorid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int sponsorid
        {
            get
            {
                return this._sponsorid;
            }
            set
            {
                this.OnsponsoridChanging(value);
                this._sponsorid = value;
                this.OnsponsoridChanged();
                this.OnPropertyChanged("sponsorid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _sponsorid;
        partial void OnsponsoridChanging(int value);
        partial void OnsponsoridChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property url in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string url
        {
            get
            {
                return this._url;
            }
            set
            {
                this.OnurlChanging(value);
                this._url = value;
                this.OnurlChanged();
                this.OnPropertyChanged("url");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _url;
        partial void OnurlChanging(string value);
        partial void OnurlChanged();
        /// <summary>
        /// There are no comments for Property imageurl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string imageurl
        {
            get
            {
                return this._imageurl;
            }
            set
            {
                this.OnimageurlChanging(value);
                this._imageurl = value;
                this.OnimageurlChanged();
                this.OnPropertyChanged("imageurl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _imageurl;
        partial void OnimageurlChanging(string value);
        partial void OnimageurlChanged();
        /// <summary>
        /// There are no comments for Property twitter in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string twitter
        {
            get
            {
                return this._twitter;
            }
            set
            {
                this.OntwitterChanging(value);
                this._twitter = value;
                this.OntwitterChanged();
                this.OnPropertyChanged("twitter");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _twitter;
        partial void OntwitterChanging(string value);
        partial void OntwitterChanged();
        /// <summary>
        /// There are no comments for Property sponsorlevelid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> sponsorlevelid
        {
            get
            {
                return this._sponsorlevelid;
            }
            set
            {
                this.OnsponsorlevelidChanging(value);
                this._sponsorlevelid = value;
                this.OnsponsorlevelidChanged();
                this.OnPropertyChanged("sponsorlevelid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _sponsorlevelid;
        partial void OnsponsorlevelidChanging(global::System.Nullable<int> value);
        partial void OnsponsorlevelidChanged();
        /// <summary>
        /// There are no comments for rooms in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<room> rooms
        {
            get
            {
                return this._rooms;
            }
            set
            {
                this._rooms = value;
                this.OnPropertyChanged("rooms");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<room> _rooms = new global::System.Data.Services.Client.DataServiceCollection<room>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<session> sessions
        {
            get
            {
                return this._sessions;
            }
            set
            {
                this._sessions = value;
                this.OnPropertyChanged("sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<session> _sessions = new global::System.Data.Services.Client.DataServiceCollection<session>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for sponsorlevel in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public sponsorlevel sponsorlevel
        {
            get
            {
                return this._sponsorlevel;
            }
            set
            {
                this._sponsorlevel = value;
                this.OnPropertyChanged("sponsorlevel");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private sponsorlevel _sponsorlevel;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for devlink2011Model.sponsorlevel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// sponsorlevelid
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("sponsorlevels")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("sponsorlevelid")]
    public partial class sponsorlevel : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new sponsorlevel object.
        /// </summary>
        /// <param name="sponsorlevelid">Initial value of sponsorlevelid.</param>
        /// <param name="name">Initial value of name.</param>
        /// <param name="sort">Initial value of sort.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static sponsorlevel Createsponsorlevel(int sponsorlevelid, string name, int sort)
        {
            sponsorlevel sponsorlevel = new sponsorlevel();
            sponsorlevel.sponsorlevelid = sponsorlevelid;
            sponsorlevel.name = name;
            sponsorlevel.sort = sort;
            return sponsorlevel;
        }
        /// <summary>
        /// There are no comments for Property sponsorlevelid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int sponsorlevelid
        {
            get
            {
                return this._sponsorlevelid;
            }
            set
            {
                this.OnsponsorlevelidChanging(value);
                this._sponsorlevelid = value;
                this.OnsponsorlevelidChanged();
                this.OnPropertyChanged("sponsorlevelid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _sponsorlevelid;
        partial void OnsponsorlevelidChanging(int value);
        partial void OnsponsorlevelidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property sort in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int sort
        {
            get
            {
                return this._sort;
            }
            set
            {
                this.OnsortChanging(value);
                this._sort = value;
                this.OnsortChanged();
                this.OnPropertyChanged("sort");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _sort;
        partial void OnsortChanging(int value);
        partial void OnsortChanged();
        /// <summary>
        /// There are no comments for sponsors in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<sponsor> sponsors
        {
            get
            {
                return this._sponsors;
            }
            set
            {
                this._sponsors = value;
                this.OnPropertyChanged("sponsors");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<sponsor> _sponsors = new global::System.Data.Services.Client.DataServiceCollection<sponsor>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for devlink2011Model.timeslot in the schema.
    /// </summary>
    /// <KeyProperties>
    /// timeslotid
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("timeslots")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("timeslotid")]
    public partial class timeslot : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new timeslot object.
        /// </summary>
        /// <param name="timeslotid">Initial value of timeslotid.</param>
        /// <param name="start">Initial value of start.</param>
        /// <param name="end">Initial value of end.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static timeslot Createtimeslot(int timeslotid, global::System.DateTime start, global::System.DateTime end)
        {
            timeslot timeslot = new timeslot();
            timeslot.timeslotid = timeslotid;
            timeslot.start = start;
            timeslot.end = end;
            return timeslot;
        }
        /// <summary>
        /// There are no comments for Property timeslotid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int timeslotid
        {
            get
            {
                return this._timeslotid;
            }
            set
            {
                this.OntimeslotidChanging(value);
                this._timeslotid = value;
                this.OntimeslotidChanged();
                this.OnPropertyChanged("timeslotid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _timeslotid;
        partial void OntimeslotidChanging(int value);
        partial void OntimeslotidChanged();
        /// <summary>
        /// There are no comments for Property start in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime start
        {
            get
            {
                return this._start;
            }
            set
            {
                this.OnstartChanging(value);
                this._start = value;
                this.OnstartChanged();
                this.OnPropertyChanged("start");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _start;
        partial void OnstartChanging(global::System.DateTime value);
        partial void OnstartChanged();
        /// <summary>
        /// There are no comments for Property end in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime end
        {
            get
            {
                return this._end;
            }
            set
            {
                this.OnendChanging(value);
                this._end = value;
                this.OnendChanged();
                this.OnPropertyChanged("end");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _end;
        partial void OnendChanging(global::System.DateTime value);
        partial void OnendChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<session> sessions
        {
            get
            {
                return this._sessions;
            }
            set
            {
                this._sessions = value;
                this.OnPropertyChanged("sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<session> _sessions = new global::System.Data.Services.Client.DataServiceCollection<session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for devlink2011Model.track in the schema.
    /// </summary>
    /// <KeyProperties>
    /// trackid
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("tracks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("trackid")]
    public partial class track : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new track object.
        /// </summary>
        /// <param name="trackid">Initial value of trackid.</param>
        /// <param name="name">Initial value of name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static track Createtrack(int trackid, string name)
        {
            track track = new track();
            track.trackid = trackid;
            track.name = name;
            return track;
        }
        /// <summary>
        /// There are no comments for Property trackid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int trackid
        {
            get
            {
                return this._trackid;
            }
            set
            {
                this.OntrackidChanging(value);
                this._trackid = value;
                this.OntrackidChanged();
                this.OnPropertyChanged("trackid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _trackid;
        partial void OntrackidChanging(int value);
        partial void OntrackidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<session> sessions
        {
            get
            {
                return this._sessions;
            }
            set
            {
                this._sessions = value;
                this.OnPropertyChanged("sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<session> _sessions = new global::System.Data.Services.Client.DataServiceCollection<session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
